#!/bin/bash

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

python shuffle.py
./run
sleep .25

