#!/bin/bash

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

python shuffle.py
./run
sleep .05

